# Generated by Django 3.2.8 on 2021-11-02 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeckOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.IntegerField()),
                ('Ref', models.IntegerField()),
                ('Style', models.CharField(max_length=255)),
                ('DateOfOrderTaken', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateOfDelivery', models.DateTimeField(default=django.utils.timezone.now)),
                ('Color', models.CharField(max_length=255)),
                ('Content_Fabric', models.CharField(max_length=255)),
                ('DownPayment', models.FloatField()),
                ('TotalPayment', models.FloatField()),
                ('Check', models.IntegerField()),
                ('BankReceipt', models.FloatField()),
                ('Shoulder', models.CharField(max_length=255)),
                ('ShoulderToWaist', models.CharField(max_length=255)),
                ('Bust', models.CharField(max_length=255)),
                ('Waist', models.CharField(max_length=255)),
                ('WaistToHip', models.CharField(max_length=255)),
                ('WaistToLength', models.CharField(max_length=255)),
                ('SleeveLength', models.CharField(max_length=255)),
                ('Cuff', models.CharField(max_length=255)),
                ('Hip', models.CharField(max_length=255)),
                ('Photo', models.FileField(blank=True, upload_to='')),
                ('NB', models.TextField()),
                ('Neck_Opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.neckopening')),
            ],
        ),
    ]
