# Generated by Django 3.2.8 on 2021-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Phone',
            field=models.CharField(max_length=255),
        ),
    ]
