# Generated by Django 3.2.8 on 2021-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_alter_record_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
