# Generated by Django 3.2.9 on 2021-11-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0005_auto_20211103_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='record',
            name='Image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Records.postimage'),
        ),
    ]
