# Generated by Django 3.2.9 on 2021-11-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0006_auto_20211103_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Records.record'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
