# Generated by Django 3.2.9 on 2021-11-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0007_auto_20211103_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='record',
        ),
    ]
